### ISSUE TITLE
Multiline concatenated string breaks check

### ISSUE THREAD

**Issue by arski** [appannie/eslint-plugin-gettext#10]
Hi there, in our code, we use Prettier with + concatenated strings when they exceed a single line, like this

<img width="691" alt="Screen Shot 2020-03-09 at 12 31 16" src="https://user-images.githubusercontent.com/904818/76213765-475e2e80-6203-11ea-9e62-eb2c14733f30.png">

This unfortunately breaks thee rule as the type of the inner node becomes a BinaryExpression (instead of a Literal), so isStringLiteral returns "false".

Would you consider adapting the check to also work for +-concatenated strings?

Thanks

**Comment by arski** [comment]
This works (need to go recursive as 'foo' + 'bar' + 'bla' is a nested structure of two-item concatenations)

```
function isStringLiteral(node) {
    if (!node) {
        return false;
    }

    if (node.type === 'Literal') {
        return typeof node.value === 'string';
    }

    if (node.type === 'BinaryExpression') {
        return node.operator === '+' && isStringLiteral(node.left) && isStringLiteral(node.right);
    }

    return false;
}
```

**Comment by BananaWanted** [comment]
Hi, @arski I'm afraid this is a case we wanted to address this plugin. `+` concatenated strings are not static. They'll prevent translation strings from being identified by translation systems. 

What we do here is simply let it exceed line width limitation, as a special case.

Another workaround is in case the string is logically separable, you may split it into smaller parts in the translation system and use it in code like this: `gettext('string part A') + gettext('string part B')`

I'm closing this thread for now. But I might be wrong. If your translation system does support binary concatenation, feel free to reopen the issue.

**Comment by arski** [comment]
Yea makes sense for a general case. It works for us because we run webpack on the code first, so the code that is actually scraped by gettext has all the strings merged already. but that's not a "normal"/default setup, so I understand you not wanting that in the main repo.

🍴 time :)
