### ISSUE TITLE
Check strings are in catalog

### ISSUE THREAD

**Issue by jayvdb** [appannie/eslint-plugin-gettext#18]
A way to find more types of errors is to check the strings exist in a .pot/.po file that is configured in the eslintrc

**Comment by SBoudrias** [comment]
Hey @jayvdb, just letting you know we're still using and maintaining the project. So this is an idea I'm supportive of. Feel free to send a PR (or someone else) and we'll help moving this along promptly :)

**Comment by jayvdb** [comment]
I've done a PR for this @SBoudrias .  It is my first eslint rule, so please rip it to shreds and I'll happily implement any improvements.

**Comment by SBoudrias** [comment]
Hey @jayvdb one thing I just realized is that your PR didn't update the README with documentation for the new rule. Would you mind adding this? Thanks!
